# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaces\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.main_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.baixar = QtWidgets.QPushButton(self.frame)
        self.baixar.setGeometry(QtCore.QRect(150, 370, 401, 20))
        self.baixar.setMinimumSize(QtCore.QSize(80, 20))
        self.baixar.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(159, 159, 159);\n"
"}")
        self.baixar.setObjectName("baixar")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(220, 220, 471, 141))
        self.frame_4.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_3.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"color: white;\n"
"border-radius: 3px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.duracao = QtWidgets.QLabel(self.frame_4)
        self.duracao.setEnabled(True)
        self.duracao.setMinimumSize(QtCore.QSize(0, 30))
        self.duracao.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.duracao.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:3px")
        self.duracao.setText("")
        self.duracao.setScaledContents(False)
        self.duracao.setObjectName("duracao")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.duracao)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_2.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"color: white;\n"
"border-radius: 3px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.titulo = QtWidgets.QLabel(self.frame_4)
        self.titulo.setEnabled(True)
        self.titulo.setMinimumSize(QtCore.QSize(0, 30))
        self.titulo.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.titulo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:3px")
        self.titulo.setText("")
        self.titulo.setScaledContents(False)
        self.titulo.setObjectName("titulo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.titulo)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(10, 220, 201, 141))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.thumb = QtWidgets.QLabel(self.frame_5)
        self.thumb.setGeometry(QtCore.QRect(16, 22, 171, 101))
        self.thumb.setText("")
        self.thumb.setObjectName("thumb")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(560, 30, 131, 21))
        self.frame_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 691, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setStyleSheet("background-color: rgb(66, 66, 66);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.url = QtWidgets.QTextEdit(self.groupBox_2)
        self.url.setObjectName("url")
        self.horizontalLayout_4.addWidget(self.url)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setStyleSheet("background-color: rgb(66, 66, 66);\n"
"color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.video = QtWidgets.QRadioButton(self.groupBox)
        self.video.setCheckable(True)
        self.video.setChecked(True)
        self.video.setObjectName("video")
        self.horizontalLayout_3.addWidget(self.video)
        self.playlist = QtWidgets.QRadioButton(self.groupBox)
        self.playlist.setObjectName("playlist")
        self.horizontalLayout_3.addWidget(self.playlist)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Baixar Videos Youtube (by Saulo Costa)"))
        self.baixar.setText(_translate("MainWindow", "BAIXAR"))
        self.pushButton_3.setText(_translate("MainWindow", "Duração"))
        self.pushButton_2.setText(_translate("MainWindow", "Título"))
        self.groupBox_2.setTitle(_translate("MainWindow", "URL"))
        self.url.setPlaceholderText(_translate("MainWindow", "url aki.."))
        self.groupBox.setTitle(_translate("MainWindow", "Tipo"))
        self.video.setText(_translate("MainWindow", "Video"))
        self.playlist.setText(_translate("MainWindow", "Playlist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
